<?php

class UsersTableSeeder extends Seeder {

    public function run()
    {
        DB::table('users')->delete();
        $users = array(
            array(
                'username' => 'hiringmanager',
                            'email' => 'test_man2@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'HM',
                            'last' => 'MANAGER',
                            'contact_number' => '0854686420',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            
            array(
                'username' => 'hrbp1',
                            'email' => 'test_man31@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'HRBP1',
                            'last' => 'ONE',
                            'contact_number' => '0883331568',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
             ),
            array(
                'username' => 'hrbp2',
                            'email' => 'test_man32@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'HRBP2',
                            'last' => 'TWO',
                            'contact_number' => '0877876533',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
             ),
            array(
                'username' => 'hrbp3',
                            'email' => 'test_man33@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'HRBP3',
                            'last' => 'THREE',
                            'contact_number' => '0812227893',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
             ),
            array(
                'username' => 'hrbp4',
                            'email' => 'test_man34@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'HRBP4',
                            'last' => 'FOUR',
                            'contact_number' => '0825372890',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
             ),
             array(
                'username' => 'recruiter4',
                            'email' => 'test_man444@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'RECRUITER4',
                            'last' => 'FOUR',
                            'contact_number' => '0821372891',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
              array(
                'username' => 'recruiter1',
                            'email' => 'test_man411@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'RECRUITER1',
                            'last' => 'ONE',
                            'contact_number' => '0871562232',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
               array(
                'username' => 'recruiter2',
                            'email' => 'test_man422@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'RECRUITER2',
                            'last' => 'TWO',
                            'contact_number' => '0851543456',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
                array(
                'username' => 'recruiter3',
                            'email' => 'test_man433@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'RECRUITER3',
                            'last' => 'THREE',
                            'contact_number' => '0812208756',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
              array(
               'username' => 'candidate1',
                            'email' => 'test_man1111@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'Peerapat',
                            'last' => 'Junkhaow',
                            'contact_number' => '0812061423',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
              array(
               'username' => 'candidate2',
                            'email' => 'northnroro@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'Napat',
                            'last' => 'Lipimongkol',
                            'contact_number' => '0822124534',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
              array(
               'username' => 'candidate3',
                            'email' => 'santacos_lala@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'Amornthip',
                            'last' => 'Rakkwamsook',
                            'contact_number' => '0803452323',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
              array(
               'username' => 'candidate4',
                            'email' => 'aii_aor@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'Boonjira',
                            'last' => 'Angsumalee',
                            'contact_number' => '0842163343',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
               array(
                 'username' => 'admin',
                            'email' => 'test_can@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'Admin',
                            'last' => 'Ad',
                            'contact_number' => '0845344534',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
                array(
                'username' => 'nexthiringmanager',
                            'email' => 'test_can2@hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'Next',
                            'last' => 'HM',
                            'contact_number' => '0836253423',
                            'confirmed' => false,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
                 array(
                 'username' => 'hrbpmanager',
                            'email' => 'test_can3hotmail.com',
                            'password' => Hash::make('test'),
                            'first' => 'HRBP',
                            'last' => 'MANAGER',
                            'contact_number' => '0827336232',
                            'confirmed' => true,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            )
        );


        DB::table('users')->insert( $users );
    }

}
